test := procedure(n) {
    print("n = $n$");
    try {
        print("check($n$ == 5)");
        check(n == 5);
        print("done!");
        return;
    } catch (e) {
        // Check whether its a real error and rethrow the error
        // if necessary.  If we don't do this, debugging will
        // be a nightmare!
        if (e != "backtrack") {
            throw(e);
        }
    }
    test(n + 1);
};

// throw an exception if condition is false
check := procedure(condition) {
    print(condition);
    if (!condition) {
        throw("backtrack");
    }
};

test(1);

